export interface SnapshotRoute {
  path: string;
  filename: string;
  screenName: string;
  state: string;
  description: string;
  requiresInteraction: boolean;
}

export const snapshotRoutes: SnapshotRoute[] = [
  {
    path: "/welcome",
    filename: "welcome.png",
    screenName: "Welcome",
    state: "mock_data",
    description: "Guía inicial de bienvenida con pasos de carga de datos",
    requiresInteraction: false,
  },
  {
    path: "/investments/tracking",
    filename: "investments-tracking.png",
    screenName: "Position Tracking",
    state: "mock_data",
    description: "Seguimiento de posiciones: evolución de cada acción desde el precio de entrada",
    requiresInteraction: false,
  },
  {
    path: "/",
    filename: "overview.png",
    screenName: "Overview",
    state: "mock_data",
    description: "Dashboard principal con patrimonio neto, liquidez, inversiones y métricas del mes",
    requiresInteraction: false,
  },
  {
    path: "/spending",
    filename: "spending.png",
    screenName: "Spending",
    state: "mock_data",
    description: "Análisis de gastos mensual con pie chart por categoría y desglose",
    requiresInteraction: false,
  },
  {
    path: "/investments",
    filename: "investments.png",
    screenName: "Investments",
    state: "mock_data",
    description: "Portfolio tracker con TR stocks, Finizens funds y cuenta remunerada",
    requiresInteraction: false,
  },
  {
    path: "/investments?tab=quality",
    filename: "investments-quality.png",
    screenName: "Investments Quality",
    state: "mock_data",
    description: "Calidad de cartera con confianza, precios, FX y posiciones manuales",
    requiresInteraction: false,
  },
  {
    path: "/investments?demo=empty",
    filename: "investments-empty.png",
    screenName: "Investments (empty)",
    state: "empty",
    description: "Estado vacío sin posiciones registradas",
    requiresInteraction: false,
  },
  {
    path: "/goals",
    filename: "goals.png",
    screenName: "Goals",
    state: "empty",
    description: "Objetivos financieros — estado inicial sin objetivos",
    requiresInteraction: false,
  },
  {
    path: "/economy",
    filename: "economy.png",
    screenName: "Economy",
    state: "empty",
    description: "Indicadores macroeconómicos — estado inicial",
    requiresInteraction: false,
  },
  {
    path: "/insights",
    filename: "insights.png",
    screenName: "Insights",
    state: "empty",
    description: "Insights personalizados — estado inicial sin análisis",
    requiresInteraction: false,
  },
  {
    path: "/imports",
    filename: "imports-empty.png",
    screenName: "Imports (empty)",
    state: "empty",
    description: "Centro de importación — estado vacío antes de seleccionar archivo",
    requiresInteraction: false,
  },
  {
    path: "/imports?demo=preview",
    filename: "imports-preview.png",
    screenName: "Imports (preview)",
    state: "preview_demo",
    description: "Centro de importación — preview y validación con datos ficticios",
    requiresInteraction: false,
  },
  {
    path: "/settings",
    filename: "settings.png",
    screenName: "Settings",
    state: "mock_data",
    description: "Configuración de la aplicación — idioma, moneda y tema",
    requiresInteraction: false,
  },
  {
    path: "/markets",
    filename: "markets.png",
    screenName: "Markets",
    state: "mock_data",
    description: "Market Watch con 36 activos en 8 categorías, tab Todos",
    requiresInteraction: false,
  },
  {
    path: "/markets?category=indices_eu",
    filename: "markets-europa.png",
    screenName: "Markets Europa",
    state: "mock_data",
    description: "Market Watch filtrado por categoría Europa",
    requiresInteraction: false,
  },
  {
    path: "/planificacion",
    filename: "planificacion.png",
    screenName: "Planificacion",
    state: "mock_data",
    description: "Planificacion con presupuestos, recurrentes asistidos y cashflow",
    requiresInteraction: false,
  },
  {
    path: "/planificacion?tab=recurrentes",
    filename: "planificacion-recurrentes.png",
    screenName: "Planificacion Recurrentes",
    state: "mock_data",
    description: "Deteccion asistida de recurrentes con candidatos confirmables",
    requiresInteraction: false,
  },
  {
    path: "/planificacion?tab=facturas",
    filename: "planificacion-facturas.png",
    screenName: "Planificacion Facturas",
    state: "mock_data",
    description: "Facturas del hogar con comparativa, anomalias y proximo recibo",
    requiresInteraction: false,
  },
  {
    path: "/transactions",
    filename: "transactions.png",
    screenName: "Transactions",
    state: "mock_data",
    description: "Ledger con busqueda, filtros, nombres legibles y acciones seguras",
    requiresInteraction: false,
  },
  {
    path: "/assistant",
    filename: "assistant.png",
    screenName: "Assistant",
    state: "provider_offline",
    description: "Copiloto IA contextual con provider local no disponible",
    requiresInteraction: false,
  },
  {
    path: "/investments/import",
    filename: "portfolio-import.png",
    screenName: "Portfolio Import",
    state: "empty",
    description: "Importacion de cartera con capturas, texto fallback y entrada manual",
    requiresInteraction: false,
  },
];
